{{ if .Values.credentials.oci.enabled }}

---
apiVersion: v1
{{- $secretNameJ := printf "oci-bucket-key-plnwn45t" }}
{{- $secretJ := (lookup "v1" "Secret" "hyperplane-jhub" $secretNameJ ) }}
{{- $secretDataJ := (get $secretJ "data") | default dict}}
data:
  {{- $filesJ := .Files }}
  {{- $ociBucketKeyJ := (get $secretDataJ "oci_bucket_key") }}
  oci_bucket_key: {{$ociBucketKeyJ | default ($filesJ.Get .Values.credentials.oci.hyperplaneServiceAccount.privateKey | b64enc)}}
  {{- $ociBucketConfJ := (get $secretDataJ "oci_config") }}
  oci_config: {{$ociBucketConfJ | default (.Values.credentials.oci.hyperplaneServiceAccount.configFile | b64enc)}}
kind: Secret
metadata:
  name: oci-bucket-key-plnwn45t
  namespace: hyperplane-jhub
type: Opaque

---
apiVersion: v1
{{- $secretNameP := printf "oci-bucket-key-plnwn45t" }}
{{- $secretP := (lookup "v1" "Secret" "hyperplane-pipelines" $secretNameP ) }}
{{- $secretDataP := (get $secretP "data") | default dict}}
data:
  {{- $filesP := .Files }}
  {{- $ociBucketKeyP := (get $secretDataP "oci_bucket_key") }}
  oci_bucket_key: {{$ociBucketKeyP | default ($filesP.Get .Values.credentials.oci.hyperplaneServiceAccount.privateKey | b64enc)}}
  {{- $ociBucketConfP := (get $secretDataP "oci_config") }}
  oci_config: {{$ociBucketConfP | default (.Values.credentials.oci.hyperplaneServiceAccount.configFile | b64enc)}}
kind: Secret
metadata:
  name: oci-bucket-key-plnwn45t
  namespace: hyperplane-pipelines
type: Opaque

{{ end }}