apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: promtail
    chart: promtail-2.0.2
    heritage: Helm
    release: loki
  name: loki-promtail
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: promtail
      release: loki
  template:
    metadata:
      annotations:
        checksum/config: 8126affdc21b3898459b547e115ac5e114fe613a0cbd651b4e3e6cab316761ab
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
      labels:
        app: promtail
        release: loki
    spec:
      affinity: {}
      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yaml
        - -client.url=http://loki.monitoring:3100/loki/api/v1/push
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: grafana/promtail:2.9.4
        imagePullPolicy: IfNotPresent
        name: promtail
        ports:
        - containerPort: 3101
          name: http-metrics
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/promtail
          name: config
        - mountPath: /run/promtail
          name: run
        - mountPath: /var/lib/docker/containers
          name: docker
          readOnly: true
        - mountPath: /var/log/pods
          name: pods
          readOnly: true
      nodeSelector: {}
      serviceAccountName: loki-promtail
      tolerations:
      - effect: NoSchedule
        key: purpose
        operator: Equal
        value: api-server
      - effect: NoSchedule
        key: purpose
        operator: Equal
        value: pipelines
      - effect: NoSchedule
        key: purpose
        operator: Equal
        value: dask-worker
      - effect: NoSchedule
        key: purpose
        operator: Equal
        value: built-in-large
      - effect: NoSchedule
        key: purpose
        operator: Equal
        value: built-in-small
      volumes:
      - configMap:
          name: loki-promtail
        name: config
      - hostPath:
          path: /run/promtail
        name: run
      - hostPath:
          path: /var/lib/docker/containers
        name: docker
      - hostPath:
          path: /var/log/pods
        name: pods
  updateStrategy: {}
