apiVersion: v1
kind: Secret
metadata:
  labels:
    app: loki
    chart: loki-2.1.1
    heritage: Helm
    release: loki
  name: loki
  namespace: monitoring
stringData:
  loki.yaml: |-
    auth_enabled: false

    # We don't want the usual /api/prom prefix.
    http_prefix:

    server:
      http_listen_port: 3100

    query_range:
      # make queries more cache-able by aligning them with their step intervals
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      # parallelise_shardable_queries: false
      results_cache:
        cache:
          # We're going to use the in-process "FIFO" cache
          enable_fifocache: true
          fifocache:
            size: 1024
            validity: 24h

    limits_config:
      max_cache_freshness_per_query: '10m'
      # parallelize queries in 15min intervals
      split_queries_by_interval: 15m
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    compactor:
      shared_store: filesystem
      working_directory: /data/loki/boltdb-shipper-compactor
    querier:
      query_ingesters_within: 1h
      engine:
        max_look_back_period: 720h
      # Most jobs durations are within 1hr.
    ingester:
      chunk_block_size: 262144
      max_chunk_age: 2h
      chunk_idle_period: 1h
      chunk_retain_period: 15m
      chunk_target_size: 1572864
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: "/tmp/wal"
    schema_config:
      configs:
      - from: "2020-10-24"
        index:
          period: 24h
          prefix: index_
        object_store: filesystem
        schema: v11
        store: boltdb-shipper
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h