apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
    chart: loki-2.1.1
    heritage: Helm
    release: loki
  name: loki
  namespace: monitoring
spec:
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: loki
    release: loki
  type: ClusterIP
