{{- if .Values.snowplow.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-logs-reader
  namespace: "istio-system"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: [pods/log]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-logs-reader
  namespace: "istio-system"
subjects:
- kind: ServiceAccount
  name: sp-subdomain-activity
  namespace: {{ .Values.defaultNamespace }}
roleRef:
  kind: Role
  name: pod-logs-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
imagePullSecrets:
- name: imagepull-gcr-service-account-key
kind: ServiceAccount
metadata:
  name: sp-subdomain-activity
  namespace: {{ .Values.defaultNamespace }}
{{- end }}