apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
  name: api-server-lz6fq80a
  namespace: hyperplane-core
spec:
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
        sidecar.istio.io/inject: "true"
        release: hyperplane-{{ .Release.Revision }}
    spec:
      nodeSelector: 
        {{.Values.nodeSelectorExpressions.key}}: {{.Values.nodeSelectorExpressions.value.hyperSys}}
      containers:
      - env:
        - name: SSH_PORTAL_PROXY
          value: ssh-portal-proxy-svc
        - name: PORT
          value: "80"
        - name: WEBHOOK_URL
          value: ""
        - name: SLACK_TOKEN
          value: ""
        - name: SLACK_CHANNEL
          value: ""
        - name: NOTIFY_SLACK
          value: "0"
        - name: HYPERPLANE_CUSTOM_DEPLOY_SECRET
          value: custom-deploy-secrets-g994i1y2
        - name: HYPERPLANE_ROOT_ALLOCATABLE_CPU
          value: {{.Values.session.defaultAllocatableCpu | quote}}
        - name: HYPERPLANE_ROOT_ALLOCATABLE_RAM
          value: {{.Values.session.defaultAllocatableRam | quote}}
        - name: HYPERPLANE_CONDA_PIPELINE_VOLUME_NAME
          value: conda-pipeline-pvc
        - name: GPU_CONDA_MOUNT
          value: {{.Values.gpuIncludeCondaMount | quote}}
        - name: CLOUD_PROVIDER
          value: {{.Values.cloudProvider}}
        - name: TRITON_MODEL_REPOSITORY_PATH
          value: triton/model_repository/
        - name: SHOW_MODEL_SERVERS
          value: "true"
        - name: HIDE_HYPERHUB_PANEL
          value: "false"
        - name: NODE_IP_IMAGE
          value: {{.Values.nodeIPImage}}
        {{- if and (.Values.credentials.azureKeyVault.enabled) (.Values.credentials.azureKeyVault.containsBucketConnectionAuth) }}
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage-connection-string
              key: access-string
        {{ end }}
        envFrom:
        - configMapRef:
            name: hyperplane-settings
        image: {{.Values.apiServer.image}}
        imagePullPolicy: IfNotPresent
        name: api-server
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
      nodeSelector:
        {{.Values.nodeSelectorExpressions.key}}: {{.Values.nodeSelectorExpressions.value.hyperSys}}
      serviceAccountName: hyperplane-operator
      tolerations:
      - effect: NoSchedule
        key: purpose
        operator: Equal
        value: api-server
