apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-server-pipelines-role-binding-pracnfqn
  namespace: hyperplane-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipelines-role-cwxtsd6t
subjects:
- kind: ServiceAccount
  name: gcr
  namespace: {{ .Values.defaultNamespace | default "hyperplane-core" | quote }}
