apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-server-role-binding-cd4g3c6l
  namespace: hyperplane-jhub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devs-role-krsb9h82
subjects:
- kind: ServiceAccount
  name: gcr
  namespace: {{ .Values.defaultNamespace | default "hyperplane-core" | quote }}
