apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-vsvc-mxhf3ugb
  namespace: hyperplane-core
spec:
  gateways:
  - {{.Values.istio.gateway}}
  hosts:
  - {{.Values.domain}}
  http:
  - match:
    - uri:
        prefix: /graphql
    route:
    - destination:
        host: api-server
        port:
          number: 80
