# {{- if eq .Values.components.includeMlflow "true" }}
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: hyperplane-mlflow
#     sidecar.istio.io/inject: "true"
#   name: hyperplane-mlflow-ees7qbvv
#   namespace: {{ .Values.defaultNamespace | default "hyperplane-core" | quote }}
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: hyperplane-mlflow
#   template:
#     metadata:
#       labels:
#         app: hyperplane-mlflow
#         sidecar.istio.io/inject: "true"
#     spec:
#       nodeSelector: 
#         {{.Values.nodeSelectorExpressions.key}}: {{.Values.nodeSelectorExpressions.value.default}}
#       containers:
#       - args:
#         - -c
#         - mlflow server --backend-store-uri {{.Values.mlflow.backendUri}} --default-artifact-root {{.Values.mlflow.defaultArtifactRoot}} --host 0.0.0.0 --port 8787
#         command:
#         - /bin/bash
#         env:
#         - name: SSH_PORTAL_PROXY
#           value: ssh-portal-proxy-svc
#         - name: WEBHOOK_URL
#           value: ""
#         - name: SLACK_TOKEN
#           value: ""
#         - name: SLACK_CHANNEL
#           value: ""
#         - name: NOTIFY_SLACK
#           value: "0"
#         - name: HYPERPLANE_GITHUB_DEPLOY_SECRET
#           value: github-deploy-key-ancrht4u
#         - name: HYPERPLANE_CUSTOM_DEPLOY_SECRET
#           value: custom-deploy-secrets-g994i1y2
#         - name: HYPERPLANE_ROOT_ALLOCATABLE_CPU
#           value: {{.Values.session.defaultAllocatableCpu | quote}}
#         - name: HYPERPLANE_ROOT_ALLOCATABLE_RAM
#           value: {{.Values.session.defaultAllocatableRam | quote}}
#         - name: HYPERPLANE_CONDA_PIPELINE_VOLUME_NAME
#           value: conda-pipeline-pvc
#         - name: GPU_CONDA_MOUNT
#           value: {{.Values.gpuIncludeCondaMount | quote}}
#         - name: CLOUD_PROVIDER
#           value: {{.Values.cloudProvider}}
#         - name: TRITON_MODEL_REPOSITORY_PATH
#           value: triton/model_repository/
#         - name: SHOW_MODEL_SERVERS
#           value: "true"
#         - name: HIDE_HYPERHUB_PANEL
#           value: "false"
#         envFrom:
#         - configMapRef:
#             name: hyperplane-settings
#         image: {{.Values.jhubBasic.image}}
#         imagePullPolicy: IfNotPresent
#         name: mlflow
#         ports:
#         - containerPort: 8787
#           name: http
#           protocol: TCP
#         volumeMounts:
#         - mountPath: /etc/gke-service-account-json
#           name: gke-service-account-json
#           readOnly: true
#       nodeSelector:
#         {{.Values.nodeSelectorExpressions.key}}: {{.Values.nodeSelectorExpressions.value.hyperSys}}
#       serviceAccountName: gcr
#       tolerations:
#       - effect: NoSchedule
#         key: purpose
#         operator: Equal
#         value: built-in-small
#       volumes:
#       - name: gke-service-account-json
#         secret:
#           defaultMode: 420
#           secretName: service-account-key-ysivp830
# {{ end }}