apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: {{ .Values.pgbouncer.namespace | default "hyperplane-pgbouncer" | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: {{.Values.pgbouncer.image}}
          ports:
            - containerPort: {{ .Values.pgbouncer.portNumber | default 6432 }}
          env:
            - name: PGBOUNCER_CONFIG_DIR
              value: {{ .Values.pgbouncer.configDir }}
            - name: POSTGRESQL_HOST
              value: {{ .Values.pgbouncer.postgresHost }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.pgbouncer.postgresPassword }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.pgbouncer.postgresDatabase }}
            - name: PGBOUNCER_PORT
              value: {{ .Values.pgbouncer.portNumber | default "6432" | quote }}
            - name: PGBOUNCER_DATABASE
              value: {{ .Values.pgbouncer.postgresDatabase }}
            - name: PGBOUNCER_POOL_MODE
              value: {{ .Values.pgbouncer.poolMode }}
            - name: PGBOUNCER_MAX_CLIENT_CONN
              value: {{ .Values.pgbouncer.maxClientConn | default "800" | quote }}
            - name: PGBOUNCER_MAX_DB_CONNECTIONS
              value: {{ .Values.pgbouncer.maxDbConnections | default "1000" | quote }}
            - name: PGBOUNCER_DEFAULT_POOL_SIZE
              value: {{ .Values.pgbouncer.defaultPoolSize | default "400" | quote }}
            - name: PGBOUNCER_MIN_POOL_SIZE
              value: {{ .Values.pgbouncer.minPoolSize | default "40" | quote }}
          resources:
            requests:
              cpu: 250m
              memory: 10Mi
            limits:
              cpu: 350m
              memory: 20Mi