apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: {{ .Values.pgbouncer.namespace | default "hyperplane-pgbouncer" | quote }}
spec:
  selector:
    app: pgbouncer
  ports:
  - protocol: TCP
    port:  {{ .Values.pgbouncer.portNumber | default 6432 }}
    targetPort:  {{ .Values.pgbouncer.portNumber | default 6432 }}
  