{{- if .Values.monitor.user_action_enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: shakudo-cluster-session-job-monitor
  name: shakudo-cluster-session-job-monitor
  namespace: {{ .Values.defaultNamespace | default "hyperplane-core" | quote }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shakudo-cluster-session-job-monitor
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shakudo-cluster-session-job-monitor
    spec:
      containers:
      - args:
        - -c
        - python /usr/local/bin/monitor/scripts/session_job_monitor.py
        command:
        - /bin/sh
        env:
        - name: HYPERPLANE_CLIENT_NAME
          value: {{ .Values.clientName }}
        - name: HYPERPLANE_API_SERVER_SERVICE_URL
          value: http://api-server.hyperplane-core.svc.cluster.local:80/graphql
        - name: SLACK_WEBHOOK
          value: https://hooks.slack.com/services/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
        - name: POLL_SECONDS
          value: "10"
        - name: HYPERPLANE__LOG_LOCATION
          value: Splunk
        - name: HYPERPLANE__LOG_SPLUNK_AUTH_TOKEN
          value: Splunk 4dc735e9-1a37-437f-9592-a01f4e6260fd
        - name: HYPERPLANE__LOG_SPLUNK_ENDPOINT
          value: https://util.splunk.quadreal.com:8088/services/collector
        image: gcr.io/devsentient-infra/feature/user-action-monitor/jhub-admin-monitor:a6f7bcc01d2a6948e47cc7366f257eb559db852b
        imagePullPolicy: Always
        name: keycloak-monitor
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: gcr
      serviceAccountName: gcr
      terminationGracePeriodSeconds: 30
{{ end }}