{{- range $role := .Values.k9s.roles -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k9s-{{ $role }}
  name: k9s-{{ $role }}
  namespace: hyperplane-core
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k9s-{{ $role }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k9s-{{ $role }}
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: k9s-{{ $role }}
      containers:
      - image: {{ $.Values.k9s.image }}
        imagePullPolicy: Always
        name: ttyd
        command:
        - /bin/sh
        args:
        - -c
        - /tmp/init.sh && ttyd --writable -p 7681 k9s
        env:
        - name: ROLE_NAME
          value: {{ $role }}
        ports:
        - name: http
          protocol: TCP
          containerPort: 7681
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
{{ end }}