{{- range $role := .Values.k9s.roles -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k9s-{{ $role }}
  namespace: hyperplane-core
imagePullSecrets:
- name: imagepull-gcr-service-account-key
{{ end }}