{{- range $role := .Values.k9s.roles -}}
---
apiVersion: v1
kind: Service
metadata:
  name: k9s-{{ $role }}
  namespace: hyperplane-core
  labels: 
    app: k9s-{{ $role }}
spec:
  type: ClusterIP
  ports:
  - port: 7681
    protocol: TCP
    targetPort: http
  selector:
    app: k9s-{{ $role }}
{{ end }}