apiVersion: v1
{{- $secret := (lookup "v1" "Secret" "hyperplane-core" "keycloak-login-pass")}}
{{- if $secret }}
{{- $secretData := (get $secret "data") | default dict}}
data:
  {{- $prevPass := (get $secretData "password") }}
  password: {{$prevPass | default (randAlphaNum 32 | b64enc)}}
{{- else }}
{{- $secret := (lookup "v1" "Secret" "hyperplane-keycloak" "keycloak-login-pass")}}
{{- $secretData := (get $secret "data") | default dict}}
data:
  {{- $prevPass := (get $secretData "password") }}
  password: {{$prevPass | default (randAlphaNum 32 | b64enc)}}
{{- end }}
kind: Secret
metadata:
  name: keycloak-login-pass
  namespace: hyperplane-core
