apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oauth2-proxy
  namespace: hyperplane-core
spec:
  gateways:
  - {{.Values.istio.gateway}}
  hosts:
  - {{.Values.domain}}
  http:
  - match:
    - uri:
        prefix: /oauth2
    route:
    - destination:
        host: oauth2-proxy.hyperplane-core.svc.cluster.local
        port:
          number: 4180
