apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-git-repo-init
  namespace: hyperplane-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: default-git-repo-init
  namespace: hyperplane-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-secret
subjects:
- kind: ServiceAccount
  name: default-git-repo-init
  namespace: hyperplane-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-secret
  namespace: hyperplane-pipelines
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-git-repo-init
  namespace: hyperplane-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-secret
subjects:
- kind: ServiceAccount
  name: default-git-repo-init
  namespace: hyperplane-pipelines 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-secret
  namespace: hyperplane-core
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
