apiVersion: v1
data:
  {{- $files := .Files }}
  {{- $secretObj := (lookup "v1" "Secret" "hyperplane-jhub" "github-deploy-key-jhub") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $idrsa := (get $secretData "id_rsa") | default ($files.Get .Values.privateKeyGit | b64enc) }}
  {{- $idrsapub := (get $secretData "id_rsa.pub") | default ($files.Get .Values.publicKeyGit | b64enc) }}
  id_rsa: {{ $idrsa | quote }}
  id_rsa.pub: {{ $idrsapub | quote }}
  known_hosts: {{(.Values.known_hosts | b64enc)}}
kind: Secret
metadata:
  name: github-deploy-key-jhub
  namespace: hyperplane-jhub
type: Opaque
---
apiVersion: v1
data:
  {{- $files := .Files }}
  {{- $secretObj := (lookup "v1" "Secret" "hyperplane-jhub" "github-deploy-key-ancrht4u") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $idrsa := (get $secretData "id_rsa") | default ($files.Get .Values.privateKeyGit | b64enc) }}
  {{- $idrsapub := (get $secretData "id_rsa.pub") | default ($files.Get .Values.publicKeyGit | b64enc) }}
  id_rsa: {{ $idrsa | quote }}
  id_rsa.pub: {{ $idrsapub | quote }}
  known_hosts: {{(.Values.known_hosts | b64enc)}}
kind: Secret
metadata:
  name: github-deploy-key-ancrht4u
  namespace: hyperplane-jhub
type: Opaque
