apiVersion: v1
imagePullSecrets:
- name: gcr-service-account-monitor-img-pull
kind: ServiceAccount
metadata:
  name: monitor-exec-sa
  namespace: {{ .Values.monitor.namespace | default "hyperplane-monitor"}}
