{{- if .Values.platformCore.devs.clusterRoleViewer }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: {{ .Values.defaultNamespace | default "hyperplane-core" | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    created-by: christine-shakudo-io
    purpose: permissions-testing
  name: cluster-viewer
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - '*'
  resources:
  - pods/exec
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- nonResourceURLs:
  - '*'
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer-role-binding-o6m04b7i
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-viewer
subjects:
- kind: ServiceAccount
  name: viewer
  namespace: {{ .Values.defaultNamespace | default "hyperplane-core" | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-viewer-role
  namespace: hyperplane-pipelines
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - patch
  - update
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewer-pipelines-role-binding
  namespace: hyperplane-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-viewer-role
subjects:
- kind: ServiceAccount
  name: viewer
  namespace: {{ .Values.defaultNamespace | default "hyperplane-core" | quote }}
# Commenting this out since we manually add this for current clusters 
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: viewer-token
#   annotations:
#     kubernetes.io/service-account.name: viewer
# type: kubernetes.io/service-account-token
{{- end }}