apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcr-conda
  namespace: hyperplane-conda

# # Only required for Azure, since it's using our image.
imagePullSecrets:
- name: imagepull-gcr-service-account-key
