# TODO: Add the values that is to be filled in by the user here.

# namespace used for the hyperplane "control panel" 
# postgres - redis - reconciler - apiserver

# ui -> hyperplane.<domain>
domain: TOREPLACEDEPLOYMENTNAME.TOREPLACEDNSNAME
clientName: TOREPLACEDEPLOYMENTNAME
domainName: TOREPLACEDEPLOYMENTNAME
clientLogoDark: "logo"
clientLogoLight: "logo"

defaultStorageClassName: standard
defaultStorageClassMode: ReadWriteOnce

pipelinePVC:
  accessModes:
  - ReadOnlyMany
  - ReadWriteOnce
  size: 50Gi
  storageClass: standard

cloudProvider: GCP

# subbing this in for the gcr serviceaccount
serviceAccountName: hyperplane

# name of pre-created secret containing docker creds

privateKeyGit: keys/id_rsa_TOREPLACEDEPLOYMENTNAME
publicKeyGit: keys/id_rsa_TOREPLACEDEPLOYMENTNAME.pub


known_hosts: |-
  github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
  git-server ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTFO5Fr+3Ijig/6I5PJfLynW3QFc81klA/uq8H/q1+3JcCGN6RikqD9b0bSHAAYEJMkR9qS6J3xz9em0wa1TzmfQirwmXbfmPLwi4zgRMQ2OPZ3F1DQCwGpQmzvCXUAfyo+hAXBtSvPRT1BLpC97fAoZgGwtAo8LWd1IebATb+h60mSZNRlCkbQbUFBorDSVb0NeaX8hsFzcoRbjJBxjhGRPDiPETGN7DhhMfrhEIyRSnuypVojO0idiipyfUsHBHV1BA87peMlpEwOtr4lqnBvzfkowEdjt/+8jezssZXpZeLmydPZhzBQLlYVIKn2rNWDUqoqdKvxDh/rk2lbiLt
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZQ5FzOPTnfADWZaN+1MF3ddYCktDCUVnaKnHIYkaqyLeHKPcrbTjjPrEZX31DWHPxwszwC3Omqf9cwRMRPF675Fch4KuCWYd8VXvjOpKDTmA2IIuevKRwq5CS/pkYlAkCVx4Ng2IREtkB/jOtZNyQdduA26HXBOtsC38R1MJwC4dNe05FsD1QCGS0pHVJIVlll/KcNW+doTkEXM25VGQS3bDc4KtwBJABAs6X6qRvbKNAPL0QZfmc+2KLViNXwd+3TaMaKFta/bAT+en2fLjxvcjDApPtxE9o8fdAEudqqVTwz91fGnVKk7v3p7Q/i4rEPGDPKViYJvLdWQtXEIax6MWei7QM6EQqIHZD5Bydqznw3cEHGIjvtgU4UgLSDSB+bx99AlrQCf7ZYyMrYGXWvNDe/W+jHqMgCHC/H935oI/4/FKqglEZ5xBU5bNkzAqiXShr+6XmMeRqyth1UKIILGF27+fDwUcI6kRwtCAM4euNQB/Gofl8X5kPxv7c8ac=
  bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
  gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
  TOREPLACEGITHUBRSAPUBKEY

gpuIncludeCondaMount: "false"

oauthClientSecret: TOREPLACEOAUTHCLIENTSECRET

nodeSelectorExpressions:
  labels:
    role: ""
  key: "hyperplane.dev/nodeType"
  value:
    hyperSys: "hyperplane-system-pool"
    default: "default-jhub-pool"
    gpu: "gpu-pool"
    dask: "dask-worker-pool"
    pipeline: "default-jobs-pool"

autoscaler:
  imageLocation: TOREPLACEIMAGELOCATION
  nodepools:
  - type: default
    min: "1"
    max: "10"
    ocid: 
  - type: dask
    min: "0"
    max: "10"
    ocid: 
  - type: gpu
    min: "0"
    max: "0"
    ocid: 

settings:
  # Used as safeguards when running
  # vertical autoscalers
  maxParallelJobs: "100"
  maxParallelSessions: "100"
  
  # where are the nodes (determines the node selector key)
  cloudProvider: "GCP"

buckets:
  gcp: TOREPLACEGCPBUCKETNAME

#imagePull:
#  gcp:
#    enabled: false
#  aws:
#    enabled: false
#  oci:
#    enabled: false

credentials:
  gcp:
    enabled: true
    hyperplaneServiceAccountJSON: keys/hyperplane-service-account.json
    clientServiceAccountJSON: keys/client-service-account.json
  oci:
    enabled: false
  aws:
    enabled: false

gitServer:
  #image: 
  #imagePullPolicy: IfNotPresent
  # === Will get deprecated. Use remoteRepoSSHUrl instead ====
  repo: git@github.com:devsentient/TOREPLACEDEPLOYMENTNAME.git
  repoUrl: --repo=git@github.com:devsentient/TOREPLACEDEPLOYMENTNAME.git
  # === Will get deprecated. Use remoteRepoSSHUrl instead ====
  remoteRepoSSHUrl: git@github.com:devsentient/TOREPLACEDEPLOYMENTNAME.git

  publicKeyString: TOREPLACEGITHUBRSAPUBKEY
  dest: monorepo
  syncBranch: main
  deployKeyName: github-deploy-key

sshportal:
  namespace: hyperplane-pipelines
  domain: TOREPLACEDEPLOYMENTNAME.TOREPLACEDNSNAME
  portal: 
    storageClassName: standard


#apiServer:
#  image: 
#  imagePullPolicy: IfNotPresent
#  istioInject: "false"

#dashboard:
#  image: 
#  imagePullPolicy: IfNotPresent
#  istioInject: "false"
#  gitStatus: "true"
#  oldRay: false
#  oldDask: false
#  includeQM: ""

#reconciler:
#  image: 
#  imagePullPolicy: IfNotPresent

#customReconciler:
#  image: 
#  imagePullPolicy: IfNotPresent

#jhubBasic:
#  image: 
#jhubDl:
#  image: 
#jhubClimate:
#  image: 
#jhubGpu:
#  image: 
#jhubSas:
#  image: 
#jhubTriton:
#  image: 
#jhubR:
#  image: 
#jhubCrypto:
#  image: 
#jhubRay:
#  image: 
#jhubRaySpark:
#  image: 
#jhubExperimental:
#  image: 

