{{- if eq .Values.cloudProvider "AWS" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{ if .Values.credentials.aws.autoscalerARN }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.credentials.aws.autoscalerARN | default (printf "arn")}}
  {{ end }}
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system
secrets:
- name: aws-autoscaling-controller-token-cg9lj
{{ end }}