apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: k9s-admin-auth
  namespace: hyperplane-core
spec:
  selector:
    matchLabels:
       app: k9s-admin
  action: ALLOW
  rules:
  - when:
    - key: request.auth.claims[resource_access][istio][roles]
      values: ["k9s-admin"]