{{- if .Values.settings.releaseNamespaceOnly }}
---
{{ else }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.monitor.namespace | default "hyperplane-monitor" | quote }}
  labels:
    hyperplane.dev/editable: enabled
{{ end }}