apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k9s-maintainer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["create", "get", delete]