{{ if .Values.customImagePullSecrets.ecr }}
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
  name: ecr-cred-helper
  namespace: hyperplane-jhub
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - |-
              ACCOUNT={{ .Values.customImagePullSecrets.ecr.awsAccountID }}
              REGION={{ .Values.customImagePullSecrets.ecr.ecrRegion }}
              SECRET_NAME=custom-image-pull-secret-jhub-ecr
              EMAIL=does.not.matter@email.com
              TOKEN=`aws ecr get-login --region ${REGION} --registry-ids ${ACCOUNT} | cut -d' ' -f6`
              echo "ENV variables setup done."
              kubectl delete secret --ignore-not-found $SECRET_NAME
              kubectl create secret docker-registry $SECRET_NAME \
              --docker-server=https://${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com \
              --docker-username=AWS \
              --docker-password="${TOKEN}" \
              --docker-email="${EMAIL}"
              echo "Secret created by name. $SECRET_NAME"
              echo "All done."
            env:
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.customImagePullSecrets.ecr.ecrRegion }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.customImagePullSecrets.ecr.secretAccessKey }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.customImagePullSecrets.ecr.accessKeyID }}
            image: odaniait/aws-kubectl:latest
            imagePullPolicy: IfNotPresent
            name: ecr-cred-helper
            resources: {}
            securityContext:
              capabilities: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: Default
          hostNetwork: true
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccount: ecr-cred-helper-serviceaccount
          serviceAccountName: ecr-cred-helper-serviceaccount
  schedule: 0 */6 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
{{ end }}
