apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vsvc-1u8k205h
  namespace: monitoring
spec:
  gateways:
  - {{.Values.istio.gateway}}
  hosts:
  - grafana.{{.Values.domain}}
  http:
  - corsPolicy:
      allowCredentials: true
      allowHeaders:
      - X-Frame-Options
      allowOrigins:
      - prefix: https://{{.Values.domain}}
      allowMethods:
      - POST
      - GET
      - OPTIONS
      maxAge: 24h
    headers:
      request:
        remove:
        - authorization
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: grafana
        port:
          number: 3000
