# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: ssh-portal-init
#   namespace: {{ .Values.namespace }} 
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding 
# metadata:
#   name: ssh-portal-init
#   namespace: {{ .Values.namespace }} 
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role 
#   name: create-secret
# subjects:
# - kind: ServiceAccount
#   name: ssh-portal-init
#   namespace: {{ .Values.namespace }} 
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role 
# metadata:
#   name: create-secret 
#   namespace: {{ .Values.namespace }} 
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - secrets
#   verbs:
#   - create
