# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: ssh-portal-policy
#   namespace: {{ .Values.namespace }}
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
#   ingress:
#   - {}