apiVersion: v1
kind: Service
metadata:
  name: ssh-portal-proxy-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ssh-portal-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8022

