apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssh-portal-role-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{.Values.portal.serviceAccount}} # Name is case sensitive
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: ssh-portal-role
  apiGroup: rbac.authorization.k8s.io
