apiVersion: v1
{{- $secretName := printf "ssh-portal-secret" }}
{{- $secret := (lookup "v1" "Secret" .Values.namespace $secretName ) }}
{{- $secretData := (get $secret "data") | default dict}}
data:
  {{- $files := .Files }}
  {{- $privateKey := (get $secretData "id_ed25519") }}
  id_ed25519: {{$privateKey | default ($files.Get .Values.privateKey | b64enc)}}

  {{- $publicKey := (get $secretData "id_ed25519.pub") }}
  id_ed25519.pub: {{$publicKey | default ($files.Get .Values.publicKey | b64enc)}}
kind: Secret
metadata:
  name: ssh-portal-secret
  namespace: {{ .Values.namespace }}
type: Opaque