# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: ssh-portal-init-scripts
#   namespace: {{ .Values.namespace }}
# data:  
#   init.sh: |
#     {{ range .Files.Lines "scripts/init-ssh-portal.sh" }}
#      {{ . }}{{ end }}
