apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipelines-cluster-role-binding-3123oi1a
  namespace: hyperplane-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-nodes-fpvu9ulb
subjects:
- kind: ServiceAccount
  name: gcr-pipelines-reconciler
  namespace: hyperplane-pipelines
