apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-logs-and-events
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
    - pods
    - events
  verbs:
    - get
    - list
- apiGroups:
  - apps
  resources:
    - deployments
  verbs:
    - get
    - list