{{ if .Values.customImagePullSecrets.ecr }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-cred-helper-role
  namespace: hyperplane-pipelines
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-cred-helper-role-binding
  namespace: hyperplane-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-cred-helper-role
subjects:
- kind: ServiceAccount
  name: ecr-cred-helper-serviceaccount
{{ end }}
