apiVersion: v1
imagePullSecrets:
- name: gcr-service-account-key-pipelines-zsaw8epg
{{ if .Values.customImagePullSecrets.ecr }}
- name: custom-image-pull-secret-pipelines-ecr
{{ end }}
{{ if .Values.customImagePullSecrets.gcr }}
- name: custom-image-pull-secret-pipelines-gcr
{{ end }}
{{ if .Values.customImagePullSecrets.dockerHub }}
- name: custom-image-pull-secret-pipelines-docker-hub
{{ end }}
{{ if .Values.customImagePullSecrets.ocir }}
- name: custom-image-pull-secret-pipelines-ocir
{{ end }}
{{ if .Values.customImagePullSecrets.acr }}
- name: custom-image-pull-secret-pipelines-acr
{{ end }}
kind: ServiceAccount
metadata:
  name: gcr-pipelines
  namespace: hyperplane-pipelines
