apiVersion: v1
imagePullSecrets:
- name: gcr-service-account-jhub-42b5pz2e
{{ if .Values.customImagePullSecrets.ecr }}
- name: custom-image-pull-secret-jhub-ecr
{{ end }}
{{ if .Values.customImagePullSecrets.gcr }}
- name: custom-image-pull-secret-jhub-gcr
{{ end }}
{{ if .Values.customImagePullSecrets.dockerHub }}
- name: custom-image-pull-secret-jhub-docker-hub
{{ end }}
{{ if .Values.customImagePullSecrets.ocir }}
- name: custom-image-pull-secret-jhub-ocir
{{ end }}
{{ if .Values.customImagePullSecrets.acr }}
- name: custom-image-pull-secret-jhub-acr
{{ end }}
kind: ServiceAccount
metadata:
  name: gcr-jhub
  namespace: hyperplane-jhub
