{{ if .Values.customImagePullSecrets.dockerHub }}
---
apiVersion: v1
kind: Secret
metadata:
  name: custom-image-pull-secret-jhub-docker-hub
  namespace: hyperplane-jhub
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": {{ printf "%s:%s" .Values.customImagePullSecrets.dockerHub.username .Values.customImagePullSecrets.dockerHub.accessToken | b64enc | quote }}
        }
      }
    }
type: kubernetes.io/dockerconfigjson
{{ end }}

{{ if .Values.customImagePullSecrets.gcr }}
---
apiVersion: v1
kind: Secret
metadata:
  name: custom-image-pull-secret-jhub-gcr
  namespace: hyperplane-jhub
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "gcr.io": {
          "username": "_json_key",
          "password": {{ .Values.customImagePullSecrets.gcr.serviceAccountKeyJson | quote }}
        }
      }
    }
type: kubernetes.io/dockerconfigjson
{{ end }}

{{ if .Values.customImagePullSecrets.ecr }}
---
apiVersion: v1
kind: Secret
metadata:
  name: custom-image-pull-secret-jhub-ecr
  namespace: hyperplane-jhub
stringData:
  .dockerconfigjson: |-
    {
      "auths": {}
    }
type: kubernetes.io/dockerconfigjson
{{ end }}

{{ if .Values.customImagePullSecrets.ocir }}
---
apiVersion: v1
kind: Secret
metadata:
  name: custom-image-pull-secret-jhub-ocir
  namespace: hyperplane-jhub
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "{{ .Values.customImagePullSecrets.ocir.regionKey }}.ocir.io": {
          "auth": {{ printf "%s/%s:%s" .Values.customImagePullSecrets.ocir.tenancyNamespace .Values.customImagePullSecrets.ocir.user .Values.customImagePullSecrets.ocir.authToken | b64enc | quote }}
        }
      }
    }
type: kubernetes.io/dockerconfigjson
{{ end }}

{{ if .Values.customImagePullSecrets.acr }}
---
apiVersion: v1
kind: Secret
metadata:
  name: custom-image-pull-secret-jhub-acr
  namespace: hyperplane-jhub
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "{{ .Values.customImagePullSecrets.acr.acrName }}.azurecr.io": {
          "auth": {{ printf "%s/%s:%s" .Values.customImagePullSecrets.acr.servicePrincipalID .Values.customImagePullSecrets.acr.servicePrincipalPassword | b64enc | quote }}
        }
      }
    }
type: kubernetes.io/dockerconfigjson
{{ end }}
