{{ if .Values.credentials.gcp.enabled }}

---
apiVersion: v1
kind: Secret
metadata:
  name: service-account-key-ysivp830
  namespace: {{ .Values.defaultNamespace | default "hyperplane-core" | quote }}
data:
  gcp-service-account-credentials.json: ''

---
apiVersion: v1
kind: Secret
metadata:
  name: hyperplane-gcr-service-account-key
  namespace: hyperplane-core
data:
  gcp-service-account-credentials.json: ''

---
apiVersion: v1
kind: Secret
metadata:
  name: service-account-key-keycloak-hfdys2v5
  namespace: hyperplane-core
data:
  gcp-service-account-credentials.json: ''

# {{- if .Values.components.includeCertManager }}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: service-account-key-certmanager-y7pshm5k
#   namespace: hyperplane-certmanager
# data:
#   gcp-service-account-credentials.json: ''
# {{ end }}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: service-account-key-conda-1w516cz7
#   namespace: hyperplane-conda
# data:
#   gcp-service-account-credentials.json: ''

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: service-account-key-client-ysivp830
#   namespace: {{ .Values.defaultNamespace | default "hyperplane-core" | quote }}
# data:
#   gcp-service-account-credentials.json: ''
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: service-account-key-pipelines-dccri9ba
#   namespace: hyperplane-pipelines
# data:
#   gcp-service-account-credentials.json: ''

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: service-account-key-jhub-sow17l42
#   namespace: hyperplane-jhub
# data:
#   gcp-service-account-credentials.json: ''

# {{ else }}

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: service-account-key-pipelines-dccri9ba
#   namespace: hyperplane-pipelines
# data:
#   gcp-service-account-credentials.json: ''

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: service-account-key-jhub-sow17l42
#   namespace: hyperplane-jhub
# data:
#   gcp-service-account-credentials.json: ''

# {{ end }}