apiVersion: v1
stringData:
  {{- $files := .Files }}
  {{- $secretObj := (lookup "v1" "Secret" "hyperplane-pipelines" "smtp-password") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $password := "" }}
  {{- if $secretData.password_value }}
  {{- $password = ($secretData.password_value | b64dec) }}
  password_value: {{ $password | quote }}
  {{- else }}
  {{- $secretObj := (lookup "v1" "Secret" "hyperplane-core" "smtp-password") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- if $secretData.password_value }}
  {{- $password = ($secretData.password_value | b64dec) }}
  password_value: {{ $password | quote }}
  {{- else }}
  {{- $password = .Values.reconciler.smtp.password }}
  password_value: {{ $password | quote }}
  {{- end }}
  {{- end }}
kind: Secret
metadata:
  name: smtp-password
  namespace: hyperplane-core
