{{- if .Values.credentials.azureKeyVault.enabled }}
#{- if .Values.credentials.azureKeyVault } { if .Values.credentials.azureKeyVault.enabled }
# This is a SecretProviderClass using user-assigned identity to access your key vault
{{- range .Values.credentials.azureKeyVault.secrets }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-hyperplane-keyvault-{{.name}}
  namespace: hyperplane-jhub
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                              # Set to true for using managed identity
    userAssignedIdentityID: {{ $.Values.credentials.azureKeyVault.clientID }} # Set the clientID of the user-assigned managed identity to use
    keyvaultName: {{ $.Values.credentials.azureKeyVault.keyVaultName }}       # Set to the name of your key vault
    cloudName: ""                                                             # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: {{.name}}
          objectType: {{.type}}
          objectVersion: ""
    tenantId: {{ $.Values.credentials.azureKeyVault.tenantID }}               # The tenant ID of the key vault
  secretObjects:                                                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: kv-secret                                                          # data field to populate
      objectName: {{.name}}                                                   # name of the mounted content to sync; this could be the object name or the object alias
    secretName: keyvault-secret-sync-{{.name}}                                # name of the Kubernetes secret object
    type: Opaque                                                              # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-hyperplane-keyvault-{{.name}}
  namespace: hyperplane-pipelines
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $.Values.credentials.azureKeyVault.clientID }}
    keyvaultName: {{ $.Values.credentials.azureKeyVault.keyVaultName }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: {{.name}}
          objectType: {{.type}}
          objectVersion: ""
    tenantId: {{ $.Values.credentials.azureKeyVault.tenantID }}
  secretObjects:
  - data:
    - key: kv-secret
      objectName: {{.name}}
    secretName: keyvault-secret-sync-{{.name}}
    type: Opaque
#{- end } { end }
{{- end }}

{{- if .Values.credentials.azureKeyVault.containsBucketConnectionAuth }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-hyperplane-keyvault-azure-storage-connection-string
  namespace: hyperplane-jhub
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $.Values.credentials.azureKeyVault.clientID }}
    keyvaultName: {{ $.Values.credentials.azureKeyVault.keyVaultName }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: placeholder-to-be-changed
          objectType: secret
          objectVersion: ""
    tenantId: {{ $.Values.credentials.azureKeyVault.tenantID }}
  secretObjects:                                   # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: access-string                           # data field to populate
      objectName: placeholder-to-be-changed        # name of the mounted content to sync; this could be the object name or the object alias
    secretName: azure-storage-connection-string    # name of the Kubernetes secret object
    type: Opaque                                   # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-hyperplane-keyvault-azure-storage-connection-string
  namespace: hyperplane-pipelines
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $.Values.credentials.azureKeyVault.clientID }}
    keyvaultName: {{ $.Values.credentials.azureKeyVault.keyVaultName }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: placeholder-to-be-changed
          objectType: secret
          objectVersion: ""
    tenantId: {{ $.Values.credentials.azureKeyVault.tenantID }}
  secretObjects:
  - data:
    - key: access-string
      objectName: placeholder-to-be-changed
    secretName: azure-storage-connection-string
    type: Opaque

{{- end }}

{{- end }}